export type ThemeId = "midnight" | "slate" | "amber-dark" | "ocean";

export interface Theme {
  id: ThemeId;
  name: string;
  description: string;
  isDark: boolean;
  vars: Record<string, string>;
}

export const THEMES: Theme[] = [
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep navy with blue accents",
    isDark: true,
    vars: {
      "--background": "#0b0d1a",
      "--foreground": "#e2e4ed",
      "--card": "#111425",
      "--card-foreground": "#e2e4ed",
      "--primary": "#4f8ff7",
      "--primary-foreground": "#ffffff",
      "--secondary": "#1a1d30",
      "--secondary-foreground": "#a0a4b8",
      "--accent": "#6c8eef",
      "--accent-foreground": "#ffffff",
      "--muted": "#151829",
      "--muted-foreground": "#6b7194",
      "--border": "#232740",
      "--ring": "#4f8ff7",
      "--destructive": "#ef4444",
      "--destructive-foreground": "#ffffff",
      "--sidebar-bg": "#090b16",
      "--gradient-orb-1": "rgba(79, 143, 247, 0.15)",
      "--gradient-orb-2": "rgba(108, 142, 239, 0.10)",
      "--gradient-orb-3": "rgba(124, 58, 237, 0.08)",
    },
  },
  {
    id: "slate",
    name: "Slate",
    description: "Clean light with blue accents",
    isDark: false,
    vars: {
      "--background": "#f5f7fa",
      "--foreground": "#1a1d2e",
      "--card": "#ffffff",
      "--card-foreground": "#1a1d2e",
      "--primary": "#3b6ff5",
      "--primary-foreground": "#ffffff",
      "--secondary": "#ebeef5",
      "--secondary-foreground": "#4a5068",
      "--accent": "#3b6ff5",
      "--accent-foreground": "#ffffff",
      "--muted": "#eef0f6",
      "--muted-foreground": "#6b728e",
      "--border": "#d5d9e4",
      "--ring": "#3b6ff5",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#ffffff",
      "--sidebar-bg": "#ebeef5",
      "--gradient-orb-1": "rgba(59, 111, 245, 0.10)",
      "--gradient-orb-2": "rgba(99, 102, 241, 0.07)",
      "--gradient-orb-3": "rgba(168, 85, 247, 0.05)",
    },
  },
  {
    id: "amber-dark",
    name: "Amber Dark",
    description: "Warm dark with gold accents",
    isDark: true,
    vars: {
      "--background": "#100d08",
      "--foreground": "#e8e0d4",
      "--card": "#181210",
      "--card-foreground": "#e8e0d4",
      "--primary": "#d4910a",
      "--primary-foreground": "#0f0a04",
      "--secondary": "#1f1810",
      "--secondary-foreground": "#b0a08a",
      "--accent": "#e8a824",
      "--accent-foreground": "#0f0a04",
      "--muted": "#1a1410",
      "--muted-foreground": "#8a7e6e",
      "--border": "#302820",
      "--ring": "#d4910a",
      "--destructive": "#ef4444",
      "--destructive-foreground": "#ffffff",
      "--sidebar-bg": "#0c0a06",
      "--gradient-orb-1": "rgba(212, 145, 10, 0.12)",
      "--gradient-orb-2": "rgba(232, 168, 36, 0.08)",
      "--gradient-orb-3": "rgba(180, 120, 20, 0.06)",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Dark teal with cyan accents",
    isDark: true,
    vars: {
      "--background": "#080f12",
      "--foreground": "#d4e8ed",
      "--card": "#0e1820",
      "--card-foreground": "#d4e8ed",
      "--primary": "#22b8cf",
      "--primary-foreground": "#041014",
      "--secondary": "#12202a",
      "--secondary-foreground": "#90b0bc",
      "--accent": "#2dd4aa",
      "--accent-foreground": "#041014",
      "--muted": "#0f1a22",
      "--muted-foreground": "#6a8e9a",
      "--border": "#1e3040",
      "--ring": "#22b8cf",
      "--destructive": "#ef4444",
      "--destructive-foreground": "#ffffff",
      "--sidebar-bg": "#060c10",
      "--gradient-orb-1": "rgba(34, 184, 207, 0.12)",
      "--gradient-orb-2": "rgba(45, 212, 170, 0.08)",
      "--gradient-orb-3": "rgba(20, 160, 200, 0.06)",
    },
  },
];

export const DEFAULT_THEME_ID: ThemeId = "midnight";
